markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
#domain: 暂时还没有域名，等以后申请到了再用 
title: 陌上尘_堤边絮
description: where there is a will, there is a way
author: kristychen
email: kristy_sunmmer#foxmail.com
github: eally-sun

config:
  js_dir:
  img_dir:
  css_dir:
